[site]
title = "Zeyu (Thomas) Liu"
description = "PhD student at the Yale University."
favicon = ""

[author]
name = "Zeyu Liu"
title = "PhD Student"
institution = "Yale University"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "zeyu.liu@yale.edu"
location = "New Haven, USA"
location_details = [
  "New Haven, USA"
]
google_scholar = "https://scholar.google.com/citations?user=hb3VtFUAAAAJ"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Baoliu"
type = "page"
target = "baoliu"
href = "/baoliu"